[package]
name = "zipy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
rand = "0.8.5"
rocket = "0.5.0-rc.2"
rocket_dyn_templates = { version = "0.1.0", features = ["tera"] }
